[build]
  command = "npm install && npm exec -w web prisma generate -- --schema ../api/prisma/schema.prisma && mkdir -p apps/web/node_modules/.prisma && cp -R apps/api/node_modules/.prisma/client apps/web/node_modules/.prisma/ && npm run build -w web"
  publish = "apps/web/dist"
  functions = "apps/web/netlify/functions"

[functions]
  external_node_modules = ["@prisma/client"]
  included_files = ["apps/web/node_modules/.prisma/client/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200